title: Study Notes
description: All my study notes
theme: just-the-docs
favicon_ico: /assets/favicon.png

url: https://mahanthathreyee.github.io/aws-notes/

aux_links:
  Notes Repository: https://github.com/mahanthathreyee/aws-notes
