name: Deploy GitHub Pages
on:
    push:
        branches:
            - main
            - feature/workflow-deployment

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "Deploy GitHub Pages"
  cancel-in-progress: true

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
            - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
            - uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
    generate-static-pages:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - name: checkout repo 
              uses: actions/checkout@v4
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            - run: pip install -r requirements.txt
            - run: mkdocs gh-deploy --force

    deploy-github-pages:
        runs-on: ubuntu-latest
        needs: [generate-static-pages]
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: checkout repo 
              uses: actions/checkout@v4
              with:
                ref: gh-pages
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
