name: Deploy GitHub Pages
on:
    push:
        branches:
            - main
            - feature/workflow-deployment

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "Deploy GitHub Pages"
  cancel-in-progress: true

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        environment: github-pages
        steps:
            - name: Configuring python 
              uses: actions/setup-python@latest
              with:
                  python-version: 3.x

            - name: Configuring cache
              run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            

            - name: Retrieving cache
              uses: actions/cache@latest
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: ~/.cache/pip
                  restore-keys: |
                      mkdocs-material-

            - name: Checkout branch
              uses: actions/checkout@latest
            
            - name: Installing Dependencies
              run: pip install -r requirements.txt

            - name: Generating static pages
              run: mkdocs gh-deploy --force

    deploy-github-pages:
        runs-on: ubuntu-latest
        needs: install-dependencies
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout to Static Site Branch
              uses: actions/checkout@latest
              with:
                ref: gh-pages

            - name: Upload Pages Artifact
              uses: actions/upload-pages-artifact@latest
              with:
                path: .

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@latest
